# Generated by Django 5.1 on 2024-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
