# Generated by Django 5.1 on 2024-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_is_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Matn')),
            ],
            options={
                'verbose_name': "📞 Biz bilan bog'laning",
                'verbose_name_plural': "📞 Biz bilan bog'laning",
            },
        ),
    ]
