# Generated by Django 5.1 on 2024-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
