# Generated by Django 5.1 on 2024-08-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
