# Generated by Django 5.1 on 2024-08-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_telegramuser_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='products', verbose_name='Mahsulot rasmi')),
                ('title', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi ?')),
            ],
        ),
    ]
