# Generated by Django 5.1 on 2024-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Narxi'),
        ),
    ]
