# Generated by Django 5.1 on 2024-08-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': "📞  Biz bilan bog'laning", 'verbose_name_plural': "📞  Biz bilan bog'laning"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Yangi'), ('approved_by_account', 'Hisobchi tomonidan tasdiqlangan'), ('approved_by_director', 'Direktor tomonidan tasdiqlangan'), ('approved_by_storekeeper', 'Omborchi tomonidan tasdiqlangan')], max_length=24, verbose_name='Buyurtma holati')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Buyurtma berilgan vaqt')),
                ('accountant_approve_time', models.DateTimeField(blank=True, null=True, verbose_name='Hisobchi tasdiqlagan vaqt')),
                ('director_approve_time', models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan vaqt')),
                ('storekeeper_approve_time', models.DateTimeField(blank=True, null=True, verbose_name='Omborchi tasdiqlagan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('qty', models.IntegerField(default=0, verbose_name='Soni')),
                ('price', models.IntegerField(default=0, verbose_name='Narxi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
