# Generated by Django 5.1 on 2024-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_contact_options_alter_product_options_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Yangi'), ('approved_by_account', 'Hisobchi tomonidan tasdiqlangan'), ('approved_by_director', 'Direktor tomonidan tasdiqlangan'), ('approved_by_storekeeper', 'Omborchi tomonidan tasdiqlangan')], default='pending', max_length=24, verbose_name='Buyurtma holati'),
        ),
    ]
